# Generated by Django 3.2.3 on 2021-12-14 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_no', models.CharField(max_length=100)),
                ('bus_manufacturer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('no_of_seats', models.IntegerField()),
                ('no_of_seats_left', models.IntegerField()),
                ('bus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporter.bus')),
            ],
        ),
    ]
