# Generated by Django 3.2.3 on 2022-05-27 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transporter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='bus_id',
        ),
        migrations.AddField(
            model_name='trip',
            name='bus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bus_id', to='transporter.bus'),
            preserve_default=False,
        ),
    ]
